---
title: "Pk/Pv/Pf Serology R Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pk_Pv_Pf_Serology_R_Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)
setup <- function(){
  needed <- c(
    "knitr", "rmarkdown", "tidyverse", "kableExtra"
  )
  for(package in needed){
    if(!sum(installed.packages() %in% package)){
      install.packages(package)
    }
    
    require(package, character.only = TRUE)
  }
}

setup()
```

```{r setup pk analysis, eval = FALSE}
library(SeroTrackR)
library(tidyverse)
```

## Step 1: Load your data! 

Firstly, we will be using our example data that's in-built in the package. Here replace the `system.file()` argument with the file path for your package. 

For a 5-point standard curve, your data will look like this: 
```{r, eval = FALSE}
your_raw_data_5std <- c(
  system.file("extdata", "example_MAGPIX_pk_5std_plate1.csv", package = "SeroTrackR"),
  system.file("extdata", "example_MAGPIX_pk_5std_plate2.csv", package = "SeroTrackR")
)
your_plate_layout_5std <- system.file("extdata", "example_platelayout_pk_5std.xlsx", package = "SeroTrackR")
```

For a 10-point standard curve, your data will look like this: 
```{r, eval = FALSE}
your_raw_data_10std <- c(
  system.file("extdata", "example_MAGPIX_pk_10std_plate1.csv", package = "SeroTrackR"),
  system.file("extdata", "example_MAGPIX_pk_10std_plate2.csv", package = "SeroTrackR")
)
your_plate_layout_10std <- system.file("extdata", "example_platelayout_pk_10std.xlsx", package = "SeroTrackR")
```

## Step 2: Run the `runPlasmoPipeline()`

### For 5-point standard curve: 
```{r, eval = FALSE}
results <- runPlasmoPipeline(
  raw_data = your_raw_data_5std,
  platform = "magpix",
  plate_layout = your_plate_layout_5std,
  panel = "panel1",
  std_point = 5, 
  experiment_name = "5-point standard curve"
)
```

### For 10-point standard curve: 
```{r, eval = FALSE}
results <- runPlasmoPipeline(
  raw_data = your_raw_data_10std,
  platform = "magpix",
  plate_layout = your_plate_layout_10std,
  panel = "panel1",
  std_point = 10, 
  experiment_name = "10-point standard curve"
)
```
